export enum LocationValues {
  BODEGAEN = 'BODEGAEN',
  DAGLIGHALLEN_BAR = 'DAGLIGHALLEN_BAR',
  EDGAR = 'EDGAR',
  KLUBBEN = 'KLUBBEN',
  LYCHE_BAR = 'LYCHE_BAR',
  LYCHE_KJOKKEN = 'LYCHE_KJOKKEN',
  RUNDHALLEN = 'RUNDHALLEN',
  SELSKAPSSIDEN = 'SELSKAPSSIDEN',
  STORSALEN = 'STORSALEN',
  STROSSA = 'STROSSA',
}
