export enum LocationValues {
  BODEGAEN = 'BODEGAEN',
  DAGLIGHALLEN_BAR = 'DAGLIGHALLEN_BAR',
  EDGAR = 'EDGAR',
  KLUBBEN = 'KLUBBEN',
  LYCHE_BAR = 'LYCHE_BAR',
  LYCHE_KJOKKEN = 'LYCHE_KJOKKEN',
  RUNDHALLEN = 'RUNDHALLEN',
  SELSKAPSSIDEN = 'SELSKAPSSIDEN',
  STORSALEN = 'STORSALEN',
  STROSSA = 'STROSSA',
}

export enum RoleValues {
  UGLE = 'UGLE',
  BRANNVAKT = 'BRANNVAKT',
  BARISTA = 'BARISTA',
  KAFEANSVARLIG = 'KAFEANSVARLIG',
  BARSERVITOR = 'BARSERVITOR',
  HOVMESTER = 'HOVMESTER',
  KOKK = 'KOKK',
  SOUSCHEF = 'SOUSCHEF',
  RYDDEVAKT = 'RYDDEVAKT',
  ARRANGEMENTBARTENDER = 'ARRANGEMENTBARTENDER',
  ARRANGEMENTANSVARLIG = 'ARRANGEMENTANSVARLIG',
  BRYGGER = 'BRYGGER',
  BARTENDER = 'BARTENDER',
  BARSJEF = 'BARSJEF',
  BARVAKT = 'BARVAKT',
  SPRITBARTENDER = 'SPRITBARTENDER',
  SPRITBARSJEF = 'SPRITBARSJEF',
}

export enum DayValues {
  MONDAY = 'MONDAY',
  TUESDAY = 'TUESDAY',
  WEDNESDAY = 'WEDNESDAY',
  THURSDAY = 'THURSDAY',
  FRIDAY = 'FRIDAY',
  SATURDAY = 'SATURDAY',
  SUNDAY = 'SUNDAY',
}
