export enum LocationValues {
  BODEGAEN = 'BODEGAEN',
  DAGLIGHALLEN_BAR = 'DAGLIGHALLEN_BAR',
  EDGAR = 'EDGAR',
  KLUBBEN = 'KLUBBEN',
  LYCHE_BAR = 'LYCHE_BAR',
  LYCHE_KJOKKEN = 'LYCHE_KJOKKEN',
  RUNDHALLEN = 'RUNDHALLEN',
  SELSKAPSSIDEN = 'SELSKAPSSIDEN',
  STORSALEN = 'STORSALEN',
  STROSSA = 'STROSSA',
}

export enum RoleValues {
  UGLE = 'UGLE',
  BRANNVAKT = 'BRANNVAKT',
  BARISTA = 'BARISTA',
  KAFEANSVARLIG = 'KAFEANSVARLIG',
  BARSERVITOR = 'BARSERVITOR',
  HOVMESTER = 'HOVMESTER',
  KOKK = 'KOKK',
  SOUSCHEF = 'SOUSCHEF',
  RYDDEVAKT = 'RYDDEVAKT',
  ARRANGEMENTBARTENDER = 'ARRANGEMENTBARTENDER',
  ARRANGEMENTANSVARLIG = 'ARRANGEMENTANSVARLIG',
  BRYGGER = 'BRYGGER',
  BARTENDER = 'BARTENDER',
  BARSJEF = 'BARSJEF',
  BARVAKT = 'BARVAKT',
  SPRITBARTENDER = 'SPRITBARTENDER',
  SPRITBARSJEF = 'SPRITBARSJEF',
}

export enum ShiftLocation {
  EDGAR = 'Edgar',
  BODEGAEN = 'Bodegaen',
  RUNDHALLEN = 'Rundhallen',
  KLUBBEN = 'Klubben',
  LYCHE_BAR = 'Lyche Bar',
  LYCHE_KJOKKEN = 'Lyche Kjøkken',
  STORSALEN = 'Storsalen',
  SELSKAPSSIDEN = 'Selskapssiden',
  STROSSA = 'Strossa',
  DAGLIGHALLEN_BAR = 'Daglighallen Bar',
}

export enum ShiftSlotRole {
  UGLE = 'Ugle',
  BRANNVAKT = 'Brannvakt',
  BARISTA = 'Barista',
  KAFEANSVARLIG = 'Kafeansvarlig',
  BARSERVITOR = 'Barservitør',
  HOVMESTER = 'Hovmester',
  KOKK = 'Kokk',
  SOUSCHEF = 'Souschef',
  RYDDEVAKT = 'Ryddevakt',
  ARRANGEMENTSBARTENDER = 'Arrangementbartender',
  ARRANGEMENTSANSVARLIG = 'Arrangementsansvarlig',
  BRYGGER = 'Brygger',
  BARTENDER = 'Bartender',
  BARSJEF = 'Barsjef',
  BARVAKT = 'Barvakt',
  SPRITBARTENDER = 'Spritbartender',
  SPRITBARSJEF = 'Spritbarsjef',
}
