name: Test workflow

on: [workflow_call]

jobs:
  test:
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        node-version: [22.16.0]

    steps:
      - uses: actions/checkout@v7

      - name: Restore dependencies cache
        uses: actions/cache@v6
        id: yarn-cache
        with:
          path: ./node_modules
          key: ${{ runner.os }}-yarn4-${{ hashFiles('yarn.lock') }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v7
        with:
          # Yarn comes from corepack later. No automatic cache from packageManager.
          package-manager-cache: false
          node-version: ${{ matrix.node-version }}

      - name: Enable corepack
        run: corepack enable

      - name: Install dependencies
        if: ${{ steps.yarn-cache.outputs.cache-hit != 'true' }}
        run: |
          yarn install --immutable

      - name: Build
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
        run: yarn build
      - name: Run tests
        run: yarn test
